window.BLUE_CRANES_ROUTES = [
  {
    "id": "surrey-hills-mini-surrey-hills",
    "title": "Mini Surrey Hills",
    "category": "Surrey Hills",
    "distanceKm": 61,
    "elevationM": 642,
    "surface": "Road",
    "effort": "Hilly",
    "start": "Richmond Park Cafe",
    "stravaUrl": "https://www.strava.com/routes/3334208682608236874",
    "sourceUrl": "https://www.londondynamo.co.uk/routes/surrey-hills/mini-surrey-hill/",
    "highlights": "Box Hill",
    "description": "A south-west hills option from Richmond Park Cafe, with Box Hill as the headline feature."
  },
  {
    "id": "surrey-hills-classic-surrey-hills-short",
    "title": "Classic Surrey Hills - Short",
    "category": "Surrey Hills",
    "distanceKm": 70,
    "elevationM": 796,
    "surface": "Road",
    "effort": "Hilly",
    "start": "Richmond Park Cafe",
    "stravaUrl": "https://www.strava.com/routes/3290738159480154370",
    "sourceUrl": "https://www.londondynamo.co.uk/routes/surrey-hills/classic-surrey-hills-short-cycling-route/",
    "highlights": "the Box Hill climb",
    "description": "A south-west hills option from Richmond Park Cafe, with the Box Hill climb as the headline feature."
  },
  {
    "id": "surrey-hills-the-barhatch-blinder",
    "title": "The Barhatch Blinder",
    "category": "Surrey Hills",
    "distanceKm": 79,
    "elevationM": 1040,
    "surface": "Road",
    "effort": "Hilly",
    "start": "Richmond Park Cafe",
    "stravaUrl": "https://www.strava.com/routes/3379458706915329342",
    "sourceUrl": "https://www.londondynamo.co.uk/routes/surrey-hills/the-barhatch-blinder-cycling-route/",
    "highlights": "the Barhatch Lane climb.",
    "description": "A south-west hills option from Richmond Park Cafe, with the Barhatch Lane climb as the headline feature."
  },
  {
    "id": "surrey-hills-leith-hill-circuit",
    "title": "Leith Hill Circuit",
    "category": "Surrey Hills",
    "distanceKm": 80,
    "elevationM": 926,
    "surface": "Road",
    "effort": "Hilly",
    "start": "Richmond Park Cafe",
    "stravaUrl": "https://www.strava.com/routes/3293950236669338036",
    "sourceUrl": "https://www.londondynamo.co.uk/routes/surrey-hills/leith-hill-circuit-cycling-route/",
    "highlights": "Leith Hill",
    "description": "A south-west hills option from Richmond Park Cafe, with Leith Hill as the headline feature."
  },
  {
    "id": "surrey-hills-shere-loop",
    "title": "Shere Loop",
    "category": "Surrey Hills",
    "distanceKm": 80,
    "elevationM": 1018,
    "surface": "Road",
    "effort": "Hilly",
    "start": "Richmond Park Cafe",
    "stravaUrl": "https://www.strava.com/routes/3332400868193884914",
    "sourceUrl": "https://www.londondynamo.co.uk/routes/surrey-hills/shere-loop-cycling-route/",
    "highlights": "a rolling series of climbs and descents",
    "description": "A south-west hills option from Richmond Park Cafe, with a rolling series of climbs and descents as the headline feature."
  },
  {
    "id": "surrey-hills-surrey-explorer-climbs-views-and-lanes",
    "title": "Surrey Explorer: Climbs, Views & Lanes",
    "category": "Surrey Hills",
    "distanceKm": 82,
    "elevationM": 1036,
    "surface": "Road",
    "effort": "Hilly",
    "start": "Richmond Park Cafe",
    "stravaUrl": "https://www.strava.com/routes/3334206226801668426",
    "sourceUrl": "https://www.londondynamo.co.uk/routes/surrey-hills/surrey-explorer-climbs-views-lanes-cycling-route/",
    "highlights": "the Shere Woodlands, Leith Hill",
    "description": "A south-west hills option from Richmond Park Cafe, with the Shere Woodlands, Leith Hill as the headline feature."
  },
  {
    "id": "surrey-hills-redhill-aerodrome-circuit",
    "title": "Redhill Aerodrome Circuit",
    "category": "Surrey Hills",
    "distanceKm": 84,
    "elevationM": 907,
    "surface": "Road",
    "effort": "Hilly",
    "start": "Richmond Park Cafe",
    "stravaUrl": "https://www.strava.com/routes/3331232776359794920",
    "sourceUrl": "https://www.londondynamo.co.uk/routes/surrey-hills/redhill-aerodrome-circuit-cycling-route/",
    "highlights": "Redhill Aerodrome",
    "description": "A south-west hills option from Richmond Park Cafe, with Redhill Aerodrome as the headline feature."
  },
  {
    "id": "surrey-hills-the-rusper-circuit",
    "title": "The Rusper Circuit",
    "category": "Surrey Hills",
    "distanceKm": 87,
    "elevationM": 866,
    "surface": "Road",
    "effort": "Hilly",
    "start": "Richmond Park Cafe",
    "stravaUrl": "https://www.strava.com/routes/3330596782343991006",
    "sourceUrl": "https://www.londondynamo.co.uk/routes/surrey-hills/the-rusper-circuit/",
    "highlights": "The road to Tanhouse Farm & Rusper",
    "description": "A south-west hills option from Richmond Park Cafe, with The road to Tanhouse Farm & Rusper as the headline feature."
  },
  {
    "id": "surrey-hills-classic-surrey-hills-long",
    "title": "Classic Surrey Hills - Long",
    "category": "Surrey Hills",
    "distanceKm": 88,
    "elevationM": 1225,
    "surface": "Road",
    "effort": "Hilly",
    "start": "Richmond Park Cafe",
    "stravaUrl": "https://www.strava.com/routes/3290740725423269336",
    "sourceUrl": "https://www.londondynamo.co.uk/routes/surrey-hills/classic-surrey-hills-long-cycling-route/",
    "highlights": "the Box Hill climb",
    "description": "A south-west hills option from Richmond Park Cafe, with the Box Hill climb as the headline feature."
  },
  {
    "id": "surrey-hills-tanhouse-and-denbies-loop",
    "title": "Tanhouse & Denbies Loop",
    "category": "Surrey Hills",
    "distanceKm": 93,
    "elevationM": 1120,
    "surface": "Road",
    "effort": "Hilly",
    "start": "Richmond Park Cafe",
    "stravaUrl": "https://www.strava.com/routes/3293286564912513428",
    "sourceUrl": "https://www.londondynamo.co.uk/routes/surrey-hills/tanhouse-denbies-loop-cycling-route/",
    "highlights": "The countryside towards Rusper.",
    "description": "A south-west hills option from Richmond Park Cafe, with The countryside towards Rusper as the headline feature."
  },
  {
    "id": "surrey-hills-the-milk-churn-loop",
    "title": "The Milk Churn Loop",
    "category": "Surrey Hills",
    "distanceKm": 107,
    "elevationM": 1147,
    "surface": "Road",
    "effort": "Hilly",
    "start": "Richmond Park Cafe",
    "stravaUrl": "https://www.strava.com/routes/3300477161029930432",
    "sourceUrl": "https://www.londondynamo.co.uk/routes/surrey-hills/the-milk-churn-loop-cycling-route/",
    "highlights": "Rolling countryside south of the Surrey Hills",
    "description": "A south-west hills option from Richmond Park Cafe, with Rolling countryside south of the Surrey Hills as the headline feature."
  },
  {
    "id": "surrey-hills-the-devil-s-punchbowl",
    "title": "The Devil's Punchbowl",
    "category": "Surrey Hills",
    "distanceKm": 116,
    "elevationM": 1188,
    "surface": "Road",
    "effort": "Hilly",
    "start": "Richmond Park Cafe",
    "stravaUrl": "https://www.strava.com/routes/3284132738836811942",
    "sourceUrl": "https://www.londondynamo.co.uk/routes/surrey-hills/the-devils-punchbowl-cycling-route/",
    "highlights": "Punchbowl Lane, The Devil's Punchbowl",
    "description": "A south-west hills option from Richmond Park Cafe, with Punchbowl Lane, The Devil's Punchbowl as the headline feature."
  },
  {
    "id": "surrey-hills-frensham-pond-loop",
    "title": "Frensham Pond Loop",
    "category": "Surrey Hills",
    "distanceKm": 123,
    "elevationM": 1165,
    "surface": "Road",
    "effort": "Hilly",
    "start": "Richmond Park Cafe",
    "stravaUrl": "https://www.strava.com/routes/3294961021643834992",
    "sourceUrl": "https://www.londondynamo.co.uk/routes/surrey-hills/frensham-pond-loop-cycling-route/",
    "highlights": "The heathland and ponds around Frensham",
    "description": "A south-west hills option from Richmond Park Cafe, with The heathland and ponds around Frensham as the headline feature."
  },
  {
    "id": "thames-valley-fairoaks-airport-loop",
    "title": "Fairoaks Airport Loop",
    "category": "Thames Valley",
    "distanceKm": 43,
    "elevationM": 137,
    "surface": "Road",
    "effort": "West",
    "start": "Richmond Park Cafe",
    "stravaUrl": "https://www.strava.com/routes/3309169025824204022",
    "sourceUrl": "https://www.londondynamo.co.uk/routes/thames-valley/fairoaks-airport-loop-cycling-route/",
    "highlights": "",
    "description": "A westbound road route from Richmond Park Cafe, useful for steadier turns, smoother roads, and a less spiky profile than the hills."
  },
  {
    "id": "thames-valley-virginia-water-loop",
    "title": "Virginia Water Loop",
    "category": "Thames Valley",
    "distanceKm": 65,
    "elevationM": 323,
    "surface": "Road",
    "effort": "West",
    "start": "Richmond Park Cafe",
    "stravaUrl": "https://www.strava.com/routes/3371898784247434728",
    "sourceUrl": "https://www.londondynamo.co.uk/routes/thames-valley/virginia-water-loop-cycling-route/",
    "highlights": "Windsor Great Park",
    "description": "A westbound road route from Richmond Park Cafe, pointing the bunch toward Windsor Great Park."
  },
  {
    "id": "thames-valley-classic-windsor-loop",
    "title": "Classic Windsor Loop",
    "category": "Thames Valley",
    "distanceKm": 74,
    "elevationM": 290,
    "surface": "Road",
    "effort": "West",
    "start": "Richmond Park Cafe",
    "stravaUrl": "https://www.strava.com/routes/3290730968456003548",
    "sourceUrl": "https://www.londondynamo.co.uk/routes/thames-valley/classic-windsor-loop-cycling-route/",
    "highlights": "Windsor Great Park",
    "description": "A westbound road route from Richmond Park Cafe, pointing the bunch toward Windsor Great Park."
  },
  {
    "id": "thames-valley-dorney-loop",
    "title": "Dorney Loop",
    "category": "Thames Valley",
    "distanceKm": 78,
    "elevationM": 244,
    "surface": "Road",
    "effort": "West",
    "start": "Richmond Park Cafe",
    "stravaUrl": "https://www.strava.com/routes/3339611401401562118",
    "sourceUrl": "https://www.londondynamo.co.uk/routes/thames-valley/dorney-loop-cycling-route/",
    "highlights": "Drift Road",
    "description": "A westbound road route from Richmond Park Cafe, pointing the bunch toward Drift Road."
  },
  {
    "id": "thames-valley-windsor-alternative-loop",
    "title": "Windsor Alternative Loop",
    "category": "Thames Valley",
    "distanceKm": 78,
    "elevationM": 442,
    "surface": "Road",
    "effort": "West",
    "start": "Richmond Park Cafe",
    "stravaUrl": "https://www.strava.com/routes/3284132949693069478",
    "sourceUrl": "https://www.londondynamo.co.uk/routes/thames-valley/windsor-alternative-loop-cycling-route/",
    "highlights": "Windsor Great Park",
    "description": "A westbound road route from Richmond Park Cafe, pointing the bunch toward Windsor Great Park."
  },
  {
    "id": "thames-valley-frimley-lodge-loop",
    "title": "Frimley Lodge Loop",
    "category": "Thames Valley",
    "distanceKm": 83,
    "elevationM": 378,
    "surface": "Road",
    "effort": "West",
    "start": "Richmond Park Cafe",
    "stravaUrl": "https://www.strava.com/routes/3338826832893646440",
    "sourceUrl": "https://www.londondynamo.co.uk/routes/thames-valley/frimley-lodge-loop-cycling-route/",
    "highlights": "The wooded roads near Frimley Lodge",
    "description": "A westbound road route from Richmond Park Cafe, pointing the bunch toward The wooded roads near Frimley Lodge."
  },
  {
    "id": "thames-valley-dragonfly-loop",
    "title": "Dragonfly Loop",
    "category": "Thames Valley",
    "distanceKm": 96,
    "elevationM": 320,
    "surface": "Road",
    "effort": "West",
    "start": "Richmond Park Cafe",
    "stravaUrl": "https://www.strava.com/routes/3338830900260131206",
    "sourceUrl": "https://www.londondynamo.co.uk/routes/thames-valley/dragonfly-loop-cycling-route/",
    "highlights": "Dinton Pastures Nature Reserve",
    "description": "A westbound road route from Richmond Park Cafe, pointing the bunch toward Dinton Pastures Nature Reserve."
  },
  {
    "id": "thames-valley-the-drifter",
    "title": "The Drifter",
    "category": "Thames Valley",
    "distanceKm": 96.2,
    "elevationM": 381,
    "surface": "Road",
    "effort": "West",
    "start": "Richmond Park Cafe",
    "stravaUrl": "https://www.strava.com/routes/3483503905380036304",
    "sourceUrl": "https://www.londondynamo.co.uk/routes/thames-valley/the-drifter-cycling-route/",
    "highlights": "Drift Road",
    "description": "A westbound road route from Richmond Park Cafe, pointing the bunch toward Drift Road."
  },
  {
    "id": "thames-valley-knowl-hill-loop",
    "title": "Knowl Hill Loop",
    "category": "Thames Valley",
    "distanceKm": 97,
    "elevationM": 404,
    "surface": "Road",
    "effort": "West",
    "start": "Richmond Park Cafe",
    "stravaUrl": "https://www.strava.com/routes/3374667054806588330",
    "sourceUrl": "https://www.londondynamo.co.uk/routes/thames-valley/knowl-hill-loop-cycling-route/",
    "highlights": "The Knowl Hill Bridleway",
    "description": "A westbound road route from Richmond Park Cafe, pointing the bunch toward The Knowl Hill Bridleway."
  },
  {
    "id": "thames-valley-twyford-drift",
    "title": "Twyford Drift",
    "category": "Thames Valley",
    "distanceKm": 101,
    "elevationM": 412,
    "surface": "Road",
    "effort": "West",
    "start": "Richmond Park Cafe",
    "stravaUrl": "https://www.strava.com/routes/3469699896996580954",
    "sourceUrl": "https://www.londondynamo.co.uk/routes/thames-valley/twyford-drift-cycling-route/",
    "highlights": "Drift Road",
    "description": "A westbound road route from Richmond Park Cafe, pointing the bunch toward Drift Road."
  },
  {
    "id": "thames-valley-henley-loop",
    "title": "Henley Loop",
    "category": "Thames Valley",
    "distanceKm": 104,
    "elevationM": 442,
    "surface": "Road",
    "effort": "West",
    "start": "Richmond Park Cafe",
    "stravaUrl": "https://www.strava.com/routes/3284133563920590840",
    "sourceUrl": "https://www.londondynamo.co.uk/routes/thames-valley/henley-loop-cycling-route/",
    "highlights": "Henley",
    "description": "A westbound road route from Richmond Park Cafe, pointing the bunch toward Henley."
  },
  {
    "id": "thames-valley-marlow-and-henley-loop",
    "title": "Marlow & Henley Loop",
    "category": "Thames Valley",
    "distanceKm": 114,
    "elevationM": 568,
    "surface": "Road",
    "effort": "West",
    "start": "Richmond Park Cafe",
    "stravaUrl": "https://www.strava.com/routes/3284133352582233080",
    "sourceUrl": "https://www.londondynamo.co.uk/routes/thames-valley/marlow-henley-loop-cycling-route/",
    "highlights": "The switchback descent into Marlow, Henley, steep climb at Cookham",
    "description": "A westbound road route from Richmond Park Cafe, pointing the bunch toward The switchback descent into Marlow, Henley, steep climb at Cookham."
  }
];
